heartbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - http://taxing.systems
    - http://mail.taxing.systems
    - http://kibana.taxing.systems
    - http://elastic.taxing.systems:9200
    - http://stack.taxing.systems:9600

- type: icmp
  schedule: '@every 5s'
  hosts:
    - elasticsearch
    - kibana
    - logstash
    - auditbeat
    - filebeat
    - heartbeat
    - metricbeat
    - packetbeat

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elastic.taxing.systems:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'

setup.ilm:
  enabled: true
  rollover_alias: "heartbeat-%{[agent.version]}-stack"
  pattern: "{now/d}-000001"

setup.kibana:
  host: "stack.taxing.systems:5601"
