heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - http://elasticsearch:9200
    - http://kibana:5601
    - http://logstash:9600

- type: icmp
  schedule: '@every 5s'
  hosts:
    - elasticsearch
    - kibana
    - logstash
    - auditbeat
    - filebeat
    - heartbeat
    - metricbeat

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'

setup.kibana:
  host: "kibana:5601"
