filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

filebeat.modules:
  - module: system
    syslog:
      enabled: true
      var.paths: [ "/hostfs/var/log/syslog.log*" ]
    auth:
      enabled: true
      var.paths: [ "/hostfs/var/log/auth.log*" ]
  - module: iptables
    log:
      enabled: true
      var.input: "file"
      var.paths: ["/hostfs/var/log/ufw.log*"]
  - module: nginx
    access:
      enabled: true
      var.paths: [ "/hostfs/var/log/nginx/access.log*" ]
    error:
      enabled: true
      var.paths: [ "/hostfs/var/log/nginx/error.log*" ]

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'

#output.logstash:
#  hosts: ["logstash:5044"]

setup.kibana:
  host: "kibana:5601"
