version: "3.8"

services:
  packetbeat:
    image: docker.elastic.co/beats/packetbeat:7.14.1
    container_name: packetbeat
    hostname: packetbeat
    cap_add:
      - "NET_ADMIN"
    #    command: -e --strict.perms=false -E setup.kibana=localhost:5601 -E output.elasticsearch.hosts=["localhost:9200"]
    command: -e --strict.perms=false
    user: packetbeat
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    volumes:
      - ./packetbeat.yml:/usr/share/packetbeat/packetbeat.yml:ro
    network_mode: host
    restart: unless-stopped
