version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic_net
    restart: unless-stopped

  logstash:
    image: docker.elastic.co/logstash/logstash:7.14.1
    container_name: logstash
    networks:
      - elastic_net
    depends_on:
      - elasticsearch
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.1
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    ports:
      - "5601:5601"
    networks:
      - elastic_net
    depends_on:
      - elasticsearch
    restart: unless-stopped

volumes:
  elastic_data:
    driver: local

networks:
  elastic_net:
    driver: bridge
