version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2G
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic_net
    restart: unless-stopped

  logstash:
    image: docker.elastic.co/logstash/logstash:7.14.1
    container_name: logstash
    hostname: logstash
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"
      - "9600:9600"
    networks:
      - elastic_net
    depends_on:
      - elasticsearch
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.1
    container_name: kibana
    hostname: kibana
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    ports:
      - "5601:5601"
    networks:
      - elastic_net
    depends_on:
      - elasticsearch
    restart: unless-stopped

  auditbeat:
    image: docker.elastic.co/beats/auditbeat:7.14.1
    container_name: auditbeat
    hostname: auditbeat
    cap_add:
      - "AUDIT_CONTROL"
      - "AUDIT_READ"
#    command: -e --strict.perms=false -E setup.kibana=kibana:5601 -E output.elasticsearch.hosts=["elasticsearch:9200"]
    command: -e --strict.perms=false
    user: root
    pid: host
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    volumes:
      - ./auditbeat/auditbeat.yml:/usr/share/auditbeat/auditbeat.yml:ro
    networks:
      - elastic_net
    depends_on:
      - elasticsearch
      - logstash
      - kibana
    restart: unless-stopped

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.14.1
    container_name: filebeat
    hostname: filebeat
#    command: -e --strict.perms=false -E setup.kibana=kibana:5601 -E output.elasticsearch.hosts=["elasticsearch:9200"]
    command: -e --strict.perms=false
    user: root
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log:/hostfs/var/log:ro
    networks:
      - elastic_net
    depends_on:
      - elasticsearch
      - logstash
      - kibana
    restart: unless-stopped

  heartbeat:
    image: docker.elastic.co/beats/heartbeat:7.14.1
    container_name: heartbeat
    hostname: heartbeat
#    command: -e --strict.perms=false -E setup.kibana=kibana:5601 -E output.elasticsearch.hosts=["elasticsearch:9200"]
    command: -e --strict.perms=false
    user: root
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    volumes:
      - ./heartbeat/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - elastic_net
    depends_on:
      - elasticsearch
      - logstash
      - kibana
    restart: unless-stopped

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.14.1
    container_name: metricbeat
    hostname: metricbeat
#    command: -e --strict.perms=false -E setup.kibana=kibana:5601 -E output.elasticsearch.hosts=["elasticsearch:9200"]
    command: -e --strict.perms=false
    user: root
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    volumes:
      - ./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    networks:
      - elastic_net
    depends_on:
      - elasticsearch
      - logstash
      - kibana
    restart: unless-stopped

  packetbeat:
    image: docker.elastic.co/beats/packetbeat:7.14.1
    container_name: packetbeat
    hostname: packetbeat
    cap_add:
      - "NET_ADMIN"
    #    command: -e --strict.perms=false -E setup.kibana=localhost:5601 -E output.elasticsearch.hosts=["localhost:9200"]
    command: -e --strict.perms=false
    user: packetbeat
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    volumes:
      - ./packetbeat/packetbeat.yml:/usr/share/packetbeat/packetbeat.yml:ro
    network_mode: host
    depends_on:
      - elasticsearch
      - logstash
      - kibana
    restart: unless-stopped

volumes:
  elastic_data:
    driver: local

networks:
  elastic_net:
    driver: bridge
